feat: add support for a open link
excalidraw/mermaid-to-excalidraw pull request #51
Opened 2024-04-10 16:52 UTC by igorwessel

Closes https://github.com/excalidraw/excalidraw/issues/7872

Mermaid provides a synyax to represent a [link without arrow head. ](https://mermaid.js.org/syntax/flowchart.html#an-open-link)

```mermaid
flowchart TD
    A((App.jsx))---B((Page.jsx))
    B-- imports ---E((Input.jsx))
    B-- imports ---F((List.jsx))
```

This Pull Request intends to introduce a feature that removes arrow heads when a specific syntax is encountered.

# Test Cases

<img width="1512" alt="Captura de Tela 2024-04-10 às 13 46 35" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/54173994/9a3c7b4b-8934-4ae0-9a93-2753ec4a185e">

<img width="1512" alt="Captura de Tela 2024-04-10 às 13 46 22" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/54173994/36cd9fcf-8384-4b3e-9676-16821aebc557">

<img width="1512" alt="Captura de Tela 2024-04-10 às 13 46 12" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/54173994/0168545b-ef25-4119-883c-5007f4960bad">

2024-04-10 18:30 UTC, gabrielduete approved these changes

2024-04-11 05:53 UTC, ad1992 requested changes
@igorwessel thank you for the contribution.
Could you make the 👇🏻 changes ?
1. Could you give descriptive names for the test case similar to how its in https://github.com/excalidraw/mermaid-to-excalidraw/blob/master/playground/testcases/sequence.ts ?
2. Also update the Changelog.md

2024-04-11 10:10 UTC, igorwessel commented
>     1. Could you give descriptive names for the test case similar to how its in [`master`/playground/testcases/sequence.ts](https://github.com/excalidraw/mermaid-to-excalidraw/blob/master/playground/testcases/sequence.ts?rgh-link-date=2024-04-11T05%3A53%3A47Z) ?

@ad1992 I've applied the same format to all the flowchart tests. Could you take a look when you get a chance? I wasn't sure about the last ones, so I labeled them as 'Complex' for now.

2024-04-12 05:00 UTC, ad1992 requested changes

2024-04-12 05:00 UTC, ad1992 commented on CHANGELOG.md
> +## 0.4.0 (2024-04-11)
```suggestion
## Unreleased
```

2024-04-12 05:00 UTC, ad1992 commented on playground/testcases/flowchart.ts
> +    name: "Direction TD",
Direction Top to Down

2024-04-12 05:00 UTC, ad1992 commented on playground/testcases/flowchart.ts
> +    name: "Direction LR",
Direction Left to Right

2024-04-12 05:01 UTC, ad1992 commented on playground/testcases/flowchart.ts
> +    name: "Direction TD",
```suggestion
    name: "Direction Top to Down",
```

2024-04-12 05:01 UTC, ad1992 commented on playground/testcases/flowchart.ts
> +    name: "Direction LR",
```suggestion
    name: "Direction Left to Right",
```

2024-04-12 05:04 UTC, ad1992 approved these changes
Looks great! Pushed some minor tweaks.
Thanks @igorwessel ✨

2024-04-12 05:05 UTC, merged